# ⚙️ 第一步：使用 Node 建置
FROM node:23 AS builder

WORKDIR /app
COPY . .

RUN npm install && npm run build

# ⚙️ 第二步：使用 Nginx 做靜態伺服器
FROM nginx:stable-alpine

# 把打包好的檔案搬進 nginx 預設靜態目錄
COPY --from=builder /app/dist /usr/share/nginx/html

# 可選：自訂 nginx 設定（例如 history fallback）
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
